### ISSUE TITLE
Screenshot script overwrites the last screenshot

### ISSUE THREAD

**Issue by Bhavye-Malhotra** [maniac-en/dotfiles#17]
**Describe the bug**
The script gave overwrites the previous screenshot while saving the other screenshot under the same minute

**To Reproduce**
1. Take a screenshot in offline mode
2. Take another screenshot under the same minute
3. This should overwrite the last saved file

**Expected behavior**
Two different files should be created

**Program version that's causing the issue:**
 - [Screenshot script](https://github.com/maniac-en/dotfiles/blob/gruvbox-dev/dotfiles/scripts/system/screenshot.sh)

**Comment by maniac-en** [comment]
#18 fixes it :)
